"""
CampusCare - PDF Management System
Generates high-quality, professional PDF reports for individual student complaints
and comprehensive administrative summary reports using ReportLab.
"""

import os
import io
import re
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.units import inch, cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    KeepTogether,
    HRFlowable
)
from reportlab.pdfgen import canvas

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ---------------- COLOR PALETTE & DESIGN SYSTEM ----------------
PRIMARY_DARK = colors.HexColor("#0F172A")     # Slate 900
PRIMARY_NAVY = colors.HexColor("#1E293B")     # Slate 800
ACCENT_BLUE = colors.HexColor("#0284C7")      # Sky 600
ACCENT_CYAN = colors.HexColor("#0EA5E9")      # Sky 500
ACCENT_LIGHT = colors.HexColor("#F0F9FF")     # Sky 50

TEXT_MAIN = colors.HexColor("#1E293B")        # Slate 800
TEXT_MUTED = colors.HexColor("#64748B")       # Slate 500
TEXT_LIGHT = colors.HexColor("#94A3B8")       # Slate 400
TEXT_WHITE = colors.HexColor("#FFFFFF")

BG_CARD = colors.HexColor("#F8FAFC")          # Slate 50
BG_ALT_ROW = colors.HexColor("#F1F5F9")       # Slate 100
BORDER_COLOR = colors.HexColor("#E2E8F0")     # Slate 200
BORDER_DARK = colors.HexColor("#CBD5E1")      # Slate 300

# Status and Priority Colors
STATUS_PENDING = colors.HexColor("#D97706")   # Amber 600
STATUS_PENDING_BG = colors.HexColor("#FFFBEB")
STATUS_PROGRESS = colors.HexColor("#2563EB")  # Blue 600
STATUS_PROGRESS_BG = colors.HexColor("#EFF6FF")
STATUS_RESOLVED = colors.HexColor("#059669")  # Emerald 600
STATUS_RESOLVED_BG = colors.HexColor("#ECFDF5")

PRIORITY_HIGH = colors.HexColor("#DC2626")    # Red 600
PRIORITY_HIGH_BG = colors.HexColor("#FEF2F2")
PRIORITY_MED = colors.HexColor("#D97706")     # Amber 600
PRIORITY_MED_BG = colors.HexColor("#FFFBEB")
PRIORITY_LOW = colors.HexColor("#0284C7")     # Sky 600
PRIORITY_LOW_BG = colors.HexColor("#F0F9FF")


# ---------------- NUMBERED CANVAS FOR DYNAMIC 2-PASS FOOTERS ----------------

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas that computes total pages dynamically and renders
    standardized institutional headers, footers, rules, and page numbers.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, total_pages):
        self.saveState()
        width, height = self._pagesize

        # Running Footer Decorative Line
        self.setStrokeColor(BORDER_COLOR)
        self.setLineWidth(0.75)
        self.line(40, 42, width - 40, 42)

        # Footer Left: System Attribution & Timestamp
        self.setFont("Helvetica", 8)
        self.setFillColor(TEXT_MUTED)
        self.drawString(
            40,
            28,
            "Generated by College Complaint & Solution Tracker  |  CampusCare Grievance Redressal System"
        )

        # Footer Right: Page Count
        page_str = f"Page {self._pageNumber} of {total_pages}"
        self.drawRightString(width - 40, 28, page_str)

        # Small security note
        self.setFont("Helvetica-Oblique", 7)
        self.setFillColor(TEXT_LIGHT)
        self.drawRightString(
            width - 40,
            16,
            "Official Institutional Record • Valid without physical signature"
        )

        self.restoreState()


# ---------------- FILENAME FORMATTER ----------------

def sanitize_filename_part(text):
    """Converts a string into a clean, safe filename token."""
    if not text:
        return "Student"
    cleaned = re.sub(r"[^\w\s-]", "", str(text)).strip()
    return re.sub(r"[-\s]+", "_", cleaned)


def get_pdf_filename(complaint_id, student_name):
    """
    Generates standardized filename: Complaint_<ComplaintID>_<StudentName>.pdf
    Example: Complaint_1023_Student_Name.pdf
    """
    safe_name = sanitize_filename_part(student_name)
    cid_str = str(complaint_id)
    return f"Complaint_{cid_str}_{safe_name}.pdf"


def get_summary_pdf_filename():
    """Generates standardized filename for summary report."""
    date_str = datetime.now().strftime("%Y-%m-%d")
    return f"Complaint_Summary_Report_{date_str}.pdf"


# ---------------- STYLESHEET BUILDER ----------------

def build_pdf_styles():
    """Builds a curated typography stylesheet for crisp, modern layout."""
    base_styles = getSampleStyleSheet()

    styles = {
        "DocTitle": ParagraphStyle(
            "DocTitle",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=20,
            textColor=PRIMARY_NAVY,
            spaceAfter=3
        ),
        "DocSubtitle": ParagraphStyle(
            "DocSubtitle",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            textColor=TEXT_MUTED,
            spaceAfter=6
        ),
        "CollegeHeader": ParagraphStyle(
            "CollegeHeader",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=PRIMARY_DARK,
            alignment=0
        ),
        "CollegeSubHeader": ParagraphStyle(
            "CollegeSubHeader",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=ACCENT_BLUE,
            alignment=0
        ),
        "SectionHeading": ParagraphStyle(
            "SectionHeading",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10.5,
            leading=14,
            textColor=PRIMARY_NAVY,
            spaceBefore=8,
            spaceAfter=4
        ),
        "FieldLabel": ParagraphStyle(
            "FieldLabel",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=TEXT_MUTED
        ),
        "FieldValue": ParagraphStyle(
            "FieldValue",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=TEXT_MAIN
        ),
        "FieldValueBold": ParagraphStyle(
            "FieldValueBold",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=PRIMARY_DARK
        ),
        "BodyText": ParagraphStyle(
            "BodyText",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13.5,
            textColor=TEXT_MAIN
        ),
        "TableHeader": ParagraphStyle(
            "TableHeader",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=TEXT_WHITE,
            alignment=0
        ),
        "TableCell": ParagraphStyle(
            "TableCell",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=TEXT_MAIN
        ),
        "TableCellBold": ParagraphStyle(
            "TableCellBold",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=11,
            textColor=PRIMARY_NAVY
        ),
        "BadgeText": ParagraphStyle(
            "BadgeText",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            alignment=1
        ),
        "RemarksBox": ParagraphStyle(
            "RemarksBox",
            parent=base_styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=9,
            leading=13,
            textColor=PRIMARY_DARK
        )
    }
    return styles


def format_location_string(complaint):
    """Combines block, floor, room, and corridor into a clean descriptive string."""
    parts = []
    block = complaint["block"] if "block" in complaint.keys() and complaint["block"] else ""
    floor_no = complaint["floor_no"] if "floor_no" in complaint.keys() and complaint["floor_no"] else ""
    room_no = complaint["room_no"] if "room_no" in complaint.keys() and complaint["room_no"] else ""
    corridor = complaint["corridor_side"] if "corridor_side" in complaint.keys() and complaint["corridor_side"] else ""
    nearby = complaint["nearby_area"] if "nearby_area" in complaint.keys() and complaint["nearby_area"] else ""

    if block:
        parts.append(f"Block: {block}")
    if floor_no:
        parts.append(f"{floor_no}")
    if room_no:
        parts.append(f"Room: {room_no}")
    if corridor:
        parts.append(f"Side: {corridor}")
    if nearby:
        parts.append(f"Near: {nearby}")

    if parts:
        return ", ".join(parts)
    return complaint["location"] if "location" in complaint.keys() and complaint["location"] else "Campus Premises"


# ---------------- INDIVIDUAL COMPLAINT PDF GENERATION ----------------

def generate_complaint_pdf(complaint, history=None, output_stream=None):
    """
    Generates a complete, professional, production-grade PDF dossier for an individual complaint.
    
    Parameters:
      complaint: sqlite3.Row or dict representing the complaint with student details.
      history: list of status history rows (optional).
      output_stream: io.BytesIO or file path. If None, returns BytesIO buffer.
    """
    buffer = output_stream if output_stream else io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=36,
        bottomMargin=54
    )

    styles = build_pdf_styles()
    story = []

    # 1. INSTITUTIONAL HEADER
    # Top Branding Bar (Two columns: College Details on left, Document Title & Date on right)
    now_str = datetime.now().strftime("%d %b %Y, %I:%M %p")
    ticket_id = complaint["ticket_id"] if "ticket_id" in complaint.keys() and complaint["ticket_id"] else f"CMP-2026-{int(complaint['complaint_id']):04d}"

    header_left = [
        Paragraph("CHANDIGARH UNIVERSITY", styles["CollegeHeader"]),
        Paragraph("College Complaint & Solution Tracker • CampusCare Portal", styles["CollegeSubHeader"]),
        Paragraph("Grievance Redressal & Student Welfare Department", styles["DocSubtitle"])
    ]

    header_right = [
        Paragraph("COMPLAINT REPORT", styles["DocTitle"]),
        Paragraph(f"<b>Ticket ID:</b> <font color='#0284C7'>{ticket_id}</font>", styles["FieldValueBold"]),
        Paragraph(f"<b>Generated:</b> {now_str}", styles["DocSubtitle"])
    ]

    header_table = Table(
        [[header_left, header_right]],
        colWidths=[310, 222]
    )
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(header_table)

    # Decorative Header Accent Line
    story.append(HRFlowable(
        width="100%",
        thickness=2,
        color=ACCENT_BLUE,
        spaceBefore=0,
        spaceAfter=10
    ))

    # 2. STATUS & PRIORITY HIGHLIGHT SUMMARY BAR
    status_str = complaint["status"] or "NEW"
    priority_str = complaint["priority"] or "Medium"

    if status_str in ["FINAL_RESOLVED", "RESOLUTION_SUBMITTED", "AWAITING_STUDENT_CONFIRMATION"]:
        s_fg, s_bg = STATUS_RESOLVED, STATUS_RESOLVED_BG
    elif status_str in ["IN_PROGRESS", "REOPENED"]:
        s_fg, s_bg = STATUS_PROGRESS, STATUS_PROGRESS_BG
    else:
        s_fg, s_bg = STATUS_PENDING, STATUS_PENDING_BG

    if priority_str == "High":
        p_fg, p_bg = PRIORITY_HIGH, PRIORITY_HIGH_BG
    elif priority_str == "Medium":
        p_fg, p_bg = PRIORITY_MED, PRIORITY_MED_BG
    else:
        p_fg, p_bg = PRIORITY_LOW, PRIORITY_LOW_BG

    status_badge_p = Paragraph(
        f"<font color='{s_fg.hexval()}'>● <b>STATUS:</b> {status_str.upper()}</font>",
        styles["FieldValueBold"]
    )
    priority_badge_p = Paragraph(
        f"<font color='{p_fg.hexval()}'>● <b>PRIORITY:</b> {priority_str.upper()}</font>",
        styles["FieldValueBold"]
    )
    category_badge_p = Paragraph(
        f"<b>CATEGORY:</b> {complaint['category']}",
        styles["FieldValueBold"]
    )
    date_badge_p = Paragraph(
        f"<b>LODGED ON:</b> {complaint['date']}",
        styles["FieldValue"]
    )

    summary_bar = Table(
        [[status_badge_p, priority_badge_p, category_badge_p, date_badge_p]],
        colWidths=[133, 133, 140, 126]
    )
    summary_bar.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BG_CARD),
        ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(summary_bar)
    story.append(Spacer(1, 10))

    # 3. COMPLAINT INFORMATION GRID
    story.append(Paragraph("1. GRIEVANCE & SUBMITTER INFORMATION", styles["SectionHeading"]))

    student_name = complaint["student_name"] if "student_name" in complaint.keys() and complaint["student_name"] else "Student"
    student_email = complaint["student_email"] if "student_email" in complaint.keys() and complaint["student_email"] else ""
    student_id = str(complaint["student_id"]) if "student_id" in complaint.keys() and complaint["student_id"] else "N/A"
    cid_str = str(complaint["complaint_id"])
    last_updated = complaint["last_updated"] if "last_updated" in complaint.keys() and complaint["last_updated"] else complaint["date"]
    location_desc = format_location_string(complaint)

    info_data = [
        [
            Paragraph("Complaint ID", styles["FieldLabel"]),
            Paragraph(f"<b>#{cid_str}</b> ({ticket_id})", styles["FieldValueBold"]),
            Paragraph("Student Name", styles["FieldLabel"]),
            Paragraph(student_name, styles["FieldValueBold"])
        ],
        [
            Paragraph("Student ID", styles["FieldLabel"]),
            Paragraph(f"UID-{student_id}", styles["FieldValue"]),
            Paragraph("Student Email", styles["FieldLabel"]),
            Paragraph(student_email or "Not recorded", styles["FieldValue"])
        ],
        [
            Paragraph("Complaint Category", styles["FieldLabel"]),
            Paragraph(complaint["category"], styles["FieldValueBold"]),
            Paragraph("Campus Block", styles["FieldLabel"]),
            Paragraph(complaint["block"] if "block" in complaint.keys() and complaint["block"] else "Campus", styles["FieldValue"])
        ],
        [
            Paragraph("Detailed Location", styles["FieldLabel"]),
            Paragraph(location_desc, styles["FieldValue"]),
            Paragraph("Submission Date", styles["FieldLabel"]),
            Paragraph(complaint["date"], styles["FieldValue"])
        ],
        [
            Paragraph("Priority Level", styles["FieldLabel"]),
            Paragraph(f"<font color='{p_fg.hexval()}'><b>{priority_str} Priority</b></font>", styles["FieldValueBold"]),
            Paragraph("Last Updated", styles["FieldLabel"]),
            Paragraph(str(last_updated), styles["FieldValue"])
        ]
    ]

    info_table = Table(info_data, colWidths=[110, 160, 110, 152])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), BG_ALT_ROW),
        ("BACKGROUND", (2, 0), (2, -1), BG_ALT_ROW),
        ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 10))

    # 4. COMPLAINT DESCRIPTION
    story.append(Paragraph("2. REPORTED ISSUE DESCRIPTION", styles["SectionHeading"]))
    desc_text = complaint["description"] or "No detailed description provided."
    clean_desc = desc_text.replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>")

    desc_table = Table(
        [[Paragraph(clean_desc, styles["BodyText"])]],
        colWidths=[532]
    )
    desc_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BG_CARD),
        ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(desc_table)
    story.append(Spacer(1, 10))

    # 5. RESOLUTION INFORMATION
    story.append(Paragraph("3. RESOLUTION & ADMINISTRATIVE ACTIONS", styles["SectionHeading"]))

    has_resolution = False
    latest_remarks = ""
    latest_resolver = "Administration"
    latest_time = str(last_updated)

    if history and len(history) > 0:
        for h in reversed(history):
            if h["remarks"] and h["remarks"].strip():
                latest_remarks = h["remarks"].strip()
                latest_resolver = h["admin_name"] or "Administration"
                latest_time = h["timestamp"] if "timestamp" in h.keys() else h["changed_at"]
                has_resolution = True
                break
        if not has_resolution and (status_str in ["IN_PROGRESS", "FINAL_RESOLVED", "RESOLUTION_SUBMITTED"]):
            has_resolution = True
            latest_remarks = f"Complaint has been placed {status_str} by university authorities."
            latest_resolver = history[-1]["admin_name"] or "Administration"
            latest_time = history[-1]["changed_at"]

    if status_str in ["FINAL_RESOLVED", "RESOLUTION_SUBMITTED", "AWAITING_STUDENT_CONFIRMATION"] or has_resolution:
        res_header = [
            [
                Paragraph("<b>Resolution Status:</b>", styles["FieldLabel"]),
                Paragraph(f"<font color='{s_fg.hexval()}'><b>{status_str}</b></font>", styles["FieldValueBold"]),
                Paragraph("<b>Action Date / Time:</b>", styles["FieldLabel"]),
                Paragraph(str(latest_time), styles["FieldValue"])
            ],
            [
                Paragraph("<b>Handled By:</b>", styles["FieldLabel"]),
                Paragraph(str(latest_resolver), styles["FieldValueBold"]),
                Paragraph("<b>Verification:</b>", styles["FieldLabel"]),
                Paragraph("✓ Verified on CampusCare System", styles["FieldValue"])
            ]
        ]
        res_header_table = Table(res_header, colWidths=[110, 160, 110, 152])
        res_header_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), BG_ALT_ROW),
            ("BACKGROUND", (2, 0), (2, -1), BG_ALT_ROW),
            ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ]))
        story.append(res_header_table)
        story.append(Spacer(1, 4))

        clean_remarks = latest_remarks.replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>") if latest_remarks else "Action taken and updated on portal."
        remarks_content = [
            Paragraph("<b>Official Admin Remarks / Resolution Details:</b>", styles["FieldLabel"]),
            Spacer(1, 3),
            Paragraph(f'"{clean_remarks}"', styles["RemarksBox"])
        ]
        remarks_table = Table([[remarks_content]], colWidths=[532])
        remarks_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), STATUS_RESOLVED_BG if status_str in ["FINAL_RESOLVED", "RESOLUTION_SUBMITTED", "AWAITING_STUDENT_CONFIRMATION"] else STATUS_PROGRESS_BG),
            ("BOX", (0, 0), (-1, -1), 1, STATUS_RESOLVED if status_str in ["FINAL_RESOLVED", "RESOLUTION_SUBMITTED", "AWAITING_STUDENT_CONFIRMATION"] else STATUS_PROGRESS),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(remarks_table)

    else:
        pending_content = [
            Paragraph("<font color='#D97706'><b>⏳ Resolution Pending</b></font>", styles["DocTitle"]),
            Spacer(1, 2),
            Paragraph(
                "This grievance ticket is currently logged in the university queue and is awaiting review and assignment "
                "by the relevant facilities management team. No resolution remarks have been recorded yet.",
                styles["BodyText"]
            )
        ]
        pending_table = Table([[pending_content]], colWidths=[532])
        pending_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), STATUS_PENDING_BG),
            ("BOX", (0, 0), (-1, -1), 1, STATUS_PENDING),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(pending_table)

    story.append(Spacer(1, 10))

    # 6. LIFECYCLE AUDIT TRAIL
    if history and len(history) > 1:
        story.append(Paragraph("4. LIFECYCLE AUDIT TRAIL & ACTIVITY LOG", styles["SectionHeading"]))
        hist_rows = [[
            Paragraph("Timestamp", styles["TableHeader"]),
            Paragraph("Updated By", styles["TableHeader"]),
            Paragraph("Transition / Status", styles["TableHeader"]),
            Paragraph("Audit Remarks", styles["TableHeader"])
        ]]

        for h in history:
            ts = h["timestamp"] if "timestamp" in h.keys() else h["changed_at"]
            who = h["admin_name"] or "System"
            old_s = h["old_status"] or "-"
            new_s = h["new_status"]
            trans = f"{old_s} → <b>{new_s}</b>" if old_s != "-" else f"<b>{new_s}</b>"
            rem = h["remarks"] or "-"
            clean_rem = rem.replace("<", "&lt;").replace(">", "&gt;")

            hist_rows.append([
                Paragraph(str(ts), styles["TableCell"]),
                Paragraph(str(who), styles["TableCellBold"]),
                Paragraph(trans, styles["TableCell"]),
                Paragraph(clean_rem, styles["TableCell"])
            ])

        hist_table = Table(hist_rows, colWidths=[105, 95, 110, 222])
        hist_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_NAVY),
            ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [TEXT_WHITE, BG_ALT_ROW]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(hist_table)
        story.append(Spacer(1, 10))

    # 7. EVIDENCE & ATTACHMENT VERIFICATION
    photo_path = complaint["photo_path"] if "photo_path" in complaint.keys() and complaint["photo_path"] else ""
    evidence_status = "Attached & Verified" if photo_path else "None Attached"

    evidence_note = Paragraph(
        f"<b>Evidence Attachment:</b> {evidence_status}" +
        (f" (File: <i>{os.path.basename(photo_path)}</i>)" if photo_path else ""),
        styles["FieldValue"]
    )
    story.append(evidence_note)

    # Build Document using NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)

    if not output_stream:
        buffer.seek(0)
        return buffer
    return output_stream


# ---------------- ADMINISTRATIVE COMPLAINT SUMMARY PDF ----------------

def generate_admin_summary_pdf(
    stats,
    category_stats,
    priority_stats,
    complaints_list,
    admin_name="Administrator",
    output_stream=None
):
    """
    Generates a comprehensive administrative summary report PDF containing:
    - Executive KPI metrics (Total, Pending, In Progress, Resolved)
    - Priority and Category breakdown analytics
    - Detailed full complaint registry table
    - Institutional headers and dynamic footers
    """
    buffer = output_stream if output_stream else io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=50
    )

    styles = build_pdf_styles()
    story = []

    # 1. HEADER
    now_str = datetime.now().strftime("%d %b %Y, %I:%M %p")
    header_left = [
        Paragraph("CHANDIGARH UNIVERSITY", styles["CollegeHeader"]),
        Paragraph("College Complaint & Solution Tracker • Admin Intelligence", styles["CollegeSubHeader"]),
        Paragraph(f"Prepared by: <b>{admin_name}</b>  |  Scope: University-Wide Grievances", styles["DocSubtitle"])
    ]

    header_right = [
        Paragraph("COMPLAINT SUMMARY REPORT", styles["DocTitle"]),
        Paragraph(f"<b>Generated On:</b> {now_str}", styles["FieldValue"]),
        Paragraph(f"<b>Total Grievances Indexed:</b> {stats.get('total', len(complaints_list))}", styles["FieldValueBold"])
    ]

    header_table = Table([[header_left, header_right]], colWidths=[310, 230])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(header_table)

    story.append(HRFlowable(
        width="100%",
        thickness=2,
        color=ACCENT_BLUE,
        spaceBefore=0,
        spaceAfter=10
    ))

    # 2. EXECUTIVE KPI SUMMARY CARDS
    story.append(Paragraph("1. EXECUTIVE GRIEVANCE OVERVIEW", styles["SectionHeading"]))

    total_c = stats.get("total", len(complaints_list))
    pending_c = stats.get("pending", 0)
    progress_c = stats.get("in_progress", 0)
    resolved_c = stats.get("resolved", 0)
    resolved_pct = round((resolved_c / total_c * 100), 1) if total_c > 0 else 0.0

    kpi_data = [
        [
            Paragraph("<font size='7' color='#64748B'><b>TOTAL GRIEVANCES</b></font><br/><font size='14' color='#0F172A'><b>" + str(total_c) + "</b></font>", styles["BadgeText"]),
            Paragraph("<font size='7' color='#D97706'><b>PENDING REVIEW</b></font><br/><font size='14' color='#D97706'><b>" + str(pending_c) + "</b></font>", styles["BadgeText"]),
            Paragraph("<font size='7' color='#2563EB'><b>IN PROGRESS</b></font><br/><font size='14' color='#2563EB'><b>" + str(progress_c) + "</b></font>", styles["BadgeText"]),
            Paragraph("<font size='7' color='#059669'><b>RESOLVED</b></font><br/><font size='14' color='#059669'><b>" + str(resolved_c) + "</b></font>", styles["BadgeText"]),
            Paragraph("<font size='7' color='#0284C7'><b>RESOLUTION RATE</b></font><br/><font size='14' color='#0284C7'><b>" + str(resolved_pct) + "%</b></font>", styles["BadgeText"]),
        ]
    ]

    kpi_table = Table(kpi_data, colWidths=[108, 108, 108, 108, 108])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), BG_CARD),
        ("BACKGROUND", (1, 0), (1, 0), STATUS_PENDING_BG),
        ("BACKGROUND", (2, 0), (2, 0), STATUS_PROGRESS_BG),
        ("BACKGROUND", (3, 0), (3, 0), STATUS_RESOLVED_BG),
        ("BACKGROUND", (4, 0), (4, 0), ACCENT_LIGHT),
        ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 12))

    # 3. STATISTICAL BREAKDOWN TABLES
    story.append(Paragraph("2. PRIORITY & CATEGORY DISTRIBUTION", styles["SectionHeading"]))

    # Priority Table
    prio_rows = [[
        Paragraph("Priority", styles["TableHeader"]),
        Paragraph("Count", styles["TableHeader"]),
        Paragraph("Share (%)", styles["TableHeader"])
    ]]
    for p in ["High", "Medium", "Low"]:
        cnt = priority_stats.get(p, 0) if isinstance(priority_stats, dict) else 0
        pct = round((cnt / total_c * 100), 1) if total_c > 0 else 0.0
        color_hex = PRIORITY_HIGH.hexval() if p == "High" else (PRIORITY_MED.hexval() if p == "Medium" else PRIORITY_LOW.hexval())
        prio_rows.append([
            Paragraph(f"<font color='{color_hex}'>● <b>{p}</b></font>", styles["TableCellBold"]),
            Paragraph(str(cnt), styles["TableCell"]),
            Paragraph(f"{pct}%", styles["TableCell"])
        ])

    prio_table = Table(prio_rows, colWidths=[90, 70, 80])
    prio_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_NAVY),
        ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [TEXT_WHITE, BG_ALT_ROW]),
        ("TOPPADDING", (0, 0), (-1, -1), 3.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))

    # Category Table
    cat_rows = [[
        Paragraph("Category", styles["TableHeader"]),
        Paragraph("Count", styles["TableHeader"]),
        Paragraph("Share (%)", styles["TableHeader"])
    ]]
    if isinstance(category_stats, dict):
        cat_items = sorted(category_stats.items(), key=lambda x: x[1], reverse=True)
    elif isinstance(category_stats, list):
        cat_items = [(item.get("category", ""), item.get("count", 0)) for item in category_stats]
    else:
        cat_items = []

    for c_name, c_cnt in cat_items:
        c_pct = round((c_cnt / total_c * 100), 1) if total_c > 0 else 0.0
        cat_rows.append([
            Paragraph(str(c_name), styles["TableCellBold"]),
            Paragraph(str(c_cnt), styles["TableCell"]),
            Paragraph(f"{c_pct}%", styles["TableCell"])
        ])

    if len(cat_rows) == 1:
        cat_rows.append([Paragraph("No categories logged", styles["TableCell"]), Paragraph("0", styles["TableCell"]), Paragraph("0%", styles["TableCell"])])

    cat_table = Table(cat_rows, colWidths=[130, 70, 80])
    cat_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_NAVY),
        ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [TEXT_WHITE, BG_ALT_ROW]),
        ("TOPPADDING", (0, 0), (-1, -1), 3.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))

    combined_stats_table = Table([[prio_table, cat_table]], colWidths=[250, 290])
    combined_stats_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(combined_stats_table)
    story.append(Spacer(1, 14))

    # 4. COMPREHENSIVE COMPLAINTS REGISTRY TABLE
    story.append(Paragraph("3. COMPREHENSIVE COMPLAINTS REGISTRY", styles["SectionHeading"]))

    table_data = [[
        Paragraph("Ticket ID", styles["TableHeader"]),
        Paragraph("Student", styles["TableHeader"]),
        Paragraph("Category", styles["TableHeader"]),
        Paragraph("Location", styles["TableHeader"]),
        Paragraph("Priority", styles["TableHeader"]),
        Paragraph("Date", styles["TableHeader"]),
        Paragraph("Status", styles["TableHeader"])
    ]]

    for row in complaints_list:
        cid = row["complaint_id"]
        tid = row["ticket_id"] if "ticket_id" in row.keys() and row["ticket_id"] else f"CMP-{cid:04d}"
        sname = row["student_name"] if "student_name" in row.keys() and row["student_name"] else f"ID: {row['student_id']}"
        cat = row["category"]
        loc = row["block"] if ("block" in row.keys() and row["block"]) else (row["location"] if "location" in row.keys() else "Campus")
        prio = row["priority"]
        dt = row["date"]
        stat = row["status"]

        if stat == "Resolved":
            st_color = STATUS_RESOLVED.hexval()
        elif stat == "In Progress":
            st_color = STATUS_PROGRESS.hexval()
        else:
            st_color = STATUS_PENDING.hexval()

        p_color = PRIORITY_HIGH.hexval() if prio == "High" else (PRIORITY_MED.hexval() if prio == "Medium" else PRIORITY_LOW.hexval())

        table_data.append([
            Paragraph(f"<b>{tid}</b>", styles["TableCellBold"]),
            Paragraph(sname, styles["TableCell"]),
            Paragraph(cat, styles["TableCell"]),
            Paragraph(loc, styles["TableCell"]),
            Paragraph(f"<font color='{p_color}'>● {prio}</font>", styles["TableCellBold"]),
            Paragraph(dt, styles["TableCell"]),
            Paragraph(f"<font color='{st_color}'><b>{stat}</b></font>", styles["TableCellBold"]),
        ])

    if len(table_data) == 1:
        table_data.append([
            Paragraph("No complaints found", styles["TableCell"]),
            Paragraph("-", styles["TableCell"]),
            Paragraph("-", styles["TableCell"]),
            Paragraph("-", styles["TableCell"]),
            Paragraph("-", styles["TableCell"]),
            Paragraph("-", styles["TableCell"]),
            Paragraph("-", styles["TableCell"]),
        ])

    registry_table = Table(
        table_data,
        colWidths=[76, 100, 85, 95, 62, 58, 64]
    )
    registry_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_NAVY),
        ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [TEXT_WHITE, BG_ALT_ROW]),
        ("TOPPADDING", (0, 0), (-1, -1), 3.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(registry_table)

    # Build summary PDF
    doc.build(story, canvasmaker=NumberedCanvas)

    if not output_stream:
        buffer.seek(0)
        return buffer
    return output_stream
